@startuml "Diagramme de classe"
package "Models" {
    class Game extends Observable {
        -pleinsdetrucs
    }

    class Item extends Observable {
        -id: number
        -alias_en: string
        -alias_fr: string

        +getId(): number
        +getAlias(): string
        -getAliasFromId(id: number): string
    }

    class Group extends Observable  {
        -id: number
        -alias_en: string
        -alias_fr: string
        -difficulty: number

        +getId(): number
        +getAlias(): string
        -getAliasFromId(id: number): string
    }

    class Observable {
        +addObserver(observer: Observer): void
        +removeObserver(observer: Observer): void
        +notifyObservers(data: any): void
    }

    Group -right- "*" Item
    Group -right- "*" Item
    Game -right- "*" Group
}

package "Views" {
    class ItemView implements Observer {
        -itemContainer: HTMLElement
        +update(item: Item): void
        +getContainer(): HTMLElement
    }

    class GroupView implements Observer {
        -groupContainer: HTMLElement
        +update(group: Group): void
        +getContainer(): HTMLElement
    }
    
    class GameView implements Observer {
        -groupView: GroupView
        -itemView: ItemView
        +update(data: any): void
    }


    interface Observer {
        +update(): void
    }
}

package "Controllers" {
    class ItemController {
        +addEventListeners(): void
    }

    class GroupController {
        +addEventListeners(): void
    }

    class GameController {
        +init(): void
    }

    ItemController --- Item
    ItemController --- ItemView

    GameController --- "*" GroupController
    GameController --- "*" ItemController
    GameController --- GameView
    GameController --- Game

    GroupController --- Group
    GroupController --- GroupView
}

Observable -right- "*" Observer

@enduml